### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by Smethan**
Progress on UI, needs more work

### CODE REVIEW

**Comment by deeppomf** [comment]
@Smethan Could you remove the .pyc files and the .gitignore?
In ui.py, a global variable gets used. Could you change your code so a global variable doesn't get used? Makes the code harder to maintain.

Will test the ui later when I have time.

**Comment by deeppomf** [comment]
Right. This pull request should be remade from a clean clone.

**Comment by deeppomf** [comment]
If you need help with general Github stuff, let me know.

**Comment by Smethan** [comment]
Ok, will do all that! I'm new to making pull requests and don't exactly know how to merge changes made after my most recent pull.

**Comment by Smethan** [comment]
Also, an idea of what kind of features would be wanted in the end UI would be helpful. Maybe you. could make an issue for keeping track of it? Not really necessary, but would be helpful

**Pull request closed without merging**
