### PR TITLE
Faster region finding, region grouping

### PR DESCRIPTION
**Pull request by Maharaghi**
Don't know if you're working on DCPv1 anymore, or if you even want these, but here are some of my changes. I would've reached out through email/dm if I could've found any, but I guess this will do.

The first major change to the code is the new region finding (region_by_mask), which is based on the mask array instead of the color. It's faster than the original region finding, at least in all the images I've tried. There might be an even better solution to this, but I don't really know how to handle lists/dicts in Python so this is what I got.

The other change is region grouping, which basically groups all the nearby found regions into a 512x512 box instead of resizing all regions individually and then using predict on each. This means that there will be some changes in how the decensoring turns out, but it will also be faster or at least equally as fast. 
On my computer, the mermaid picture looks a bit worse with the grouping, but other pictures look better. I tried some other real censored pictures and got mixed results there too. 
If you want to see some comparisons I'd have to ask you to tell me where I can reach you, since I can't really upload them here. 
I also have a branch with just the faster region finding if grouping doesn't suit this.

Here's a picture of what the grouping does. Feel free to try it yourself if you want, I added the new changes in \_\_main\_\_ in utils.py, but you might have to uncomment the grouping part.
grouping

Also it seems like my editor made a lot of minor changes such as spaces before comments... sorry.
After writing all of this I realized maybe I should post an issue first asking about this, but screw it.

Thanks.

### CODE REVIEW

**Comment by ccppoo** [comment]
I think you should  leave comments, those are guide for others. Even It could look messy though

**Comment by Maharaghi** [comment]
Yea I should really comment. I didn't really plan on sharing this code at first tbh.
Is this change something you want though? If it is I'll make comments and such, but if it isn't we could just close this pull request. If you just want the new region finder I'll just make a new branch that only adds that function and comment it. Let me know what you want or don't want.

**Comment by ccppoo** [comment]
deeppomf could check it in a week maybe if there's no big deal. and I'm just one of contributors, it's just a comment.
That region detecting were used for counting regions colored by (0,0,255) to count how many regions detected, not a major feature.
But to make clear, **showing those censored areas in a group could be vague for users checking if it's censored in a right way (colored with 0,0,255)**.

**Comment by Maharaghi** [comment]
I'm not quite sure what you mean, sorry. The region detection is used to create the expanded bounding boxes in both the original code and this one, so that the program knows what to crop and predict right? My new function `region_by_mask` simply finds these regions faster, at least in all images I've tried it on. If you were referring to the other new function `find_color_regions`, then that was a function I made before deeppomf's `find_regions` function allowed for a set mask_color, and I just forgot to remove it when making this pull request.

I think I see what you mean about the grouping being vague, but this could be solved by uncommenting some code in the \_\_main\_\_ function of utils. The image will then look like this. You can remove the grouping boxes too if you'd like. 
group

Is there a way we can talk with a live chat instead or something, since I'm very bad at trying to explain things...
Hopefully I made things at least a bit clearer to what the changes I did actually do.

**Comment by ccppoo** [comment]
What I meant vague is... Those boxing is for developer running utils.py (who could read python codes) to check 0,0,255 regions. So if some one tries some kind of debugging, checking if DCP is catching those areas properly, the original seems more better. Because it shows one by one. 

there's no need to talk privately,

**Comment by Maharaghi** [comment]
But this change doesn't have to change that function at all. You can just disable showing the big boxes and it will display like the original. The first picture is using the new region finder, and the second one is using the old one. I don't really see the problem with the display options. I get that it might be a problem with decensoring when using grouping, since this model isn't trained with it, but debugging should not be a problem at all.
group
nogroup

I'm sorry if I come across as rude, that is not my intention. I really respect this project because it got me interested in these kinds of things.

**Comment by ccppoo** [comment]
So did I got interested by this project, nothing emotional,  all fine. If my replies felt kind of rude never intentional sorry, I should also take some time on this project after exam season ends... thanks for your codes

**Comment by Maharaghi** [comment]
It's okay, I think we just misunderstood what we wanted.
For now I'll make some comments and edit the code and wait until deeppomf answers, if he/she does. If not, then it's not a big deal. This was mostly made for personal use anyway.
Thanks for taking your time to respond :)

**Comment by deeppomf** [comment]
Thanks for your PR @Maharaghi .
I'll test the region finder you implemented when I have time.
Region grouping doesn't fit in my vision for DCP. The neural network is trained to decensor crops of single censored regions. Region grouping changes the input into crops containing multiple censored regions, which the neural network was not trained on.

**Comment by Maharaghi** [comment]
Yea, retraining with grouping would take a lot of extra time so I can understand that.
Do you want me to change the PR so it only includes the region change, or are you going to copy the code manually to test? It's only a single function after all, so either way works.

**Comment by deeppomf** [comment]
Change the PR to only include the region code.

**Pull request merged**
